version: "3.7"
services:
  markkubot_dev:
    image: markkubot_dev:latest
    env_file: .env
    depends_on:
    - db
    restart: always
  db:
    image: postgres
    env_file:
      - .env
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
