version: "3.3"
services:
  markkubot:
    image: markkubot:2.0.7
    env_file: .env
    depends_on:
    - db
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_USER: eltsu7
      POSTGRES_PASSWORD: kaljaa
      POSTGRES_DB: markku
    ports:
    - "5432:5432"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
