tips = [
    "Reeniä reeniä!",
    "Laita kohde varjoon!",
    "Vaihda canoniin!",
    "Vaihda nikoniin!",
    "Vaihda sonyyn!",
    "Vaihda smenaan!",
    "Horisontti suoraan!",
    "Nosta tummaa alapäätä.",
    "Aina voi vetää mustavalkoseks.",
    "Osta kalliimpi kamera!",
    "vitsisauna.preset",
    "'No ei se väline siinä oo se oleellinen. Mul on ykköset sit muista syistä.'\n-Petri Mast 2018",
    "Kuvaisit filmiä.",
    "Jos ei oo mallia niin aina voi kuvata omia jalkoja.",
    "Yhtäkään raajaa ei leikata!",
    "Clarity aina 100.",
    "Kultainen leikkaus tai mene roskiin.",
    "1.4 ei himmennetä koskaan.",
    "1.4 voi joskus himmentää.",
    "Älä käytä sigmaa oikeissa kuvauksissa!",
    "Älä käytä f22, kun kuvaat makroja. Diffraktio on vittumainen suure.",
    "Parhaat kuvat sisältää aina vähän syntiä ;)",
    "Muistakaa käyttää P(rofessional)-modee!",
    "Kovalevytila on halpaa ja pilvipalvelut rajattomia <3",
    "Valovoima on ylivoimaa.",
    "Laskeudu koiran tasolle.",
    "Pidä kädessäsi lelua tai ruokaa ja heiluttele sitä linssin ympärillä.",
    "Kärsivällisyyttä.",
    "Älä osta presettejä. Tee niitä itse.",
    "Sammuta kamera kun irroitat vakaajallista putkea.",
    "Manuaalilla ku tarkentaa niin aina osuu.",
    "Kyllä sillä roskalavalta noukitulla keksipurkillakin saa kunnon kuvaa osaavissa käsissä.",
    "Joistakin malleista ei millään saa elävän tuntuisia kuvia. Tällöin yksi cocktail auttaa hyvän tuloksen saamiseksi paremmin kuin yhden voimakkaan lampun antama lisävalo.",
    "Mitä vaikeempi asento sen taiteellisempi kuva.",
    "Gammasäteily ei häikäise.",
    "Paras kamera ei ole kaikille sama.",
    "Osta sääkin oma Smenas, ne ei paljon maksa!",
    "Tarkista kaikkien kameroiden kellot ennen ku alat vetää.",
    "Kuivaa jalusta huolella jos uitat sen kokonaan järvessä.",
    "Treenaa pohkeita.",
    "Mene mukaan tilanteisiin hienovaraisesti.",
    "Smenalla: Aukko f/11 tai 16, tarkennus mieluummin ylä- kun alakanttiin.",
    "Isolla aukolla vain jos on pakko.",
    "Servo päälle ja nappi pohjaan ja kotona sitten katotaan kuvat.",
    "Skannaa mieluusti negat muualla ko keittiössä, staattinen sähkö vetään puoleensa leivänmuruja.",
    "Kameroita ei voi olla ikinä liikaa.",
    "Passikuvan voi ottaa vaikka puhelimella kotona, siin ei oo kovat vaatimukset.",
    "Julkaiskaa enemmän, saa palautetta ja myöhemmin saa myötistellä eiku siis näkee kuinka on kehittyny kuvaajana.",
    'Yksi konsti spiraaliongelmissa on lyödä spiraali napakasti pari kertaa pöytään. Tärähdys saa filmin siellä loppupäässä "rentoutumaan" ja taas kulkemaan.',
    "Älä myy vanhaa kuvauskalustoa liian äkkinäisesti pois, se saattaa kaduttaa jälkeenpäin. Filmikaman arvo tuskin laskee vaikka miettisit pari vuotta.",
    "'Buzz, this is Houston. F/2 - 1/160th second for shadow photography on the sequence camera.'\n-Apollo 11 Mission Control, 109:23:26",
    "Kaamoksen taittaa iso kuvakoko, mustavalkofilmi ja vedenpitävät jalkineet.",
    "Vain peilin kolahduksesta läsnäoleva yleisö tietää, että paikalla on myös oikea ammatti_kuvaaja.",
    "Hyvän tarjouksen tullessa vastaan kannattaa ostaa heti. Jos et osta heti, joku muu sen kyllä ostaa pois. Ja nettikaupasta ostettaessa kannattaa muistaa palautusoikeus tavaroille.",
    "Kääri moottoripyörän kahvanlämmitinmattoa kameran rungon ja putken ympärille jos näpit jäätyy talvella",
    "Eihän sitä harrastajakuvaaja muita kun testikuvia kuvaakaan",
    "Myyntihetki ajoitetaan perikunnan toimesta",
    "Sijoita kerralla parempaan runkoon, jonka kanssa pärjäät useamman vuoden.",
    "Älä osta f/1.8 objektiiveja koska pian tarvitset kuitenkin f/1.4.",
    "Älä aseta kolmijalkaa minkään automaattisesti liikkuvan taakse",
    "Huonolla ilmalla tulee parhaat kuvat",
    "Kun olet käyttänyt 10k€ kalustoon, on aika opetella kuvaamaan",
    "Neliössä kaikki on aina vähän keskemmällä.",
    "Pöh! Valokuvaus on jalo taiteenlaji, joka palkitsee tekijänsä. Sen parissa köyhäkin sielu kultivoituu. \n - Aku Ankka",
    "Aloittelijan ei kannata hamstrata kaikkia lisävarusteita kerralla, mutta taitojen karttuessa tarpeellisia osia voivat olla ainakin muistikortti",
    "ISO 12800:aa pienempi on vaan terävyyttä",
    'Autot kuvataan "aina" sellaselt korkeudelt et näkyy ali :) \n - Mestari',
    "Kuvassa on luonnetta kun se on vähän ohi tarkennettu.",
    "Ammu vain HP5+. Ei tarvi miettiä.",
    "Laita aina kolmijalan yksi jalka linssin suuntaan. Jos jalusta kaatuu, niin se ei ainakaan rysähdä suoraan etuelementti edellä asfalttiin.",
    "Pieni tähtäysreikä keskelle reflaa, niin on helppo suunnata oikein.",
    "Muistakaa printata hyvät kuvanne.",
    "Muiden filmiperiä ei avata ilman lupaa!",
    "Lämmitä kehite suljetussa astiassa. Vituttaa kun keitinlasi kaatuu vesihauteeseen.",
    "Sunny16 on se, kun aurinko paistaa niin, että silmiin sattuu. Sit, jos ei satu, stoppi vähemmän.",
    "Ei ikinä Sastamalaan ilman kamerakalustoa",
    "Skumppapullo on muuten paljon helpompi pitää kuvatessa kädessä kuin tuoppi.",
    "Luonto ei toista itseään. Jos näet hyvän aiheen hyvällä valolla, ja ajattelet että kuvaan tuon huomenna, ei onnistu. Huomenna se on aivan erilainen, ja jää kuva saamatta.",
    "Silmillä voi tallentaa ja nauttia ympäristöstä ilman, että kamera on koko ajan kädessä.",
    "Ammattilainen ei napsi eikä räpsi. Hän hakee kuvat.",
    "Kissanpentuja kuvatessa väsytä ne leikkimällä ensiksi. Sen jälkeen ne jopa saattaa pysyä paikoillaan sen hetken.",
    "Tarkista valkotasapaino ennen kun kuvaat videota",
    "Mokat voi paikkailla sitten editissä.",
    "24fps, 1/50s ja kovaa ajoa.",
    "Varmista että kuvakoko vaihtuu tai kuvakulma muuttuu riittävästi, jos leikkaat saman kohteen kuvien välillä",
    "Käynnistä REC vasta kun klaffi on kuvassa. Tällöin se näkyy videon previkassa suoraan.",
    "Akkujen ja muistikorttien kanssa +1 -periaate, mukaan yksi enemmän kuin luulet tarvitsevasi",
    "Valokuvaus on yksi iso f-luvun maksimointitehtävä.",
    "Lightroomin print-osasto on ihan näppärä jos haluu esim järkkärikuvistaan pdf:ää. Tosta vaan valitsee kuvat jotka haluu samaan tiedostoon ja painaa print.",
    "Kinohommissa kyllä todennu että se fiilis kuvatessa on kaikista tärkein.",
    "Kameratorilla siihen tuotteeseen laitetaan arvoa testaamalla ja parhaassa tapauksessa huoltamalla se.",
    "Treenaa forkkuja.",
    "Odota että ryhmä ehtii kuvaan ennen ku kutsut seuraavan.",
    "Jos f/4 ahdistaa niin f/2.8 on kyllä turha päivitys.",
    "Jos yrityksesi lähetys pitää tullata, jätä tulli-ilmoituksen tekeminen suosiolla rahtiyritykselle.",
    "Tarkenna aina lähimpään silmään.",
    "Käytä Fairya tai muuta nestemäistä astianpesuainetta filmin loppuhuuhtelun yhteydessä. Saat valumajäljettömän filmin ja kehitetankin pestyä samalla kertaa.",
    "Vain kalleimmat kamat on parhaat.",
    "Experiences don't have to be positive as long as they are strong.",
    "Älä säilytä oluttölkkiä kameralaukussa.",
    "Jatka videon tallennusta aina muutama sekunti pidempään kuin pidät tarpeellisena.",
    "Jos löydät houkuttelevan tarjouksen, sovi kaupat välittömästi ja mieti logistiikkaa vasta sen jälkeen.",
    "Oikeisiin kuvauksiin sit Canonit.",
    "Kun kuvaat lumista maisemaa niin muista kompensoida valotusta vähintään yhdellä stopilla.",
    "Jos lähdet kuvaamaan ja filmissä on jäljellä vähemmän kuin viisi ruutua, vaihda filmi.",
    "Voit ajatella ton ostamisen sijoituksena inspiraatioon",
    "Pidä akut pakkasella sisätaskussa.",
    "Aika antaa arkiselle kuvalle arvon.",
    "Torikuvan urlista kun vaihtaa loppuun original, niin saa hieman isomman kuvan: https://images.tori.fi/api/v1/imagestori/images/6171628697.jpg?rule=original",
    "Parhaat kuvat otetaan huonolla kelillä.",
    "Tärkeintä on se, että\n-kamera sopii omaan käteen\n-rungon hinta ja tulevien lasien hinta sopii omalle lompakolle\n-akkukesto jos jostain syystä kuvaat jotain infernaalisen pitkii settejä\n-kameran käyttöliittymä ei saa sua hermostumaan\n-antaa kaiken muun paskan speksivertailun olla",
    "Kaiken taiteen tehtävä ei ole miellyttää.",
    "Visualisoi kuva mielessäsi ennen laukaisua.",
    "Zoomaus on hyvä piilottaa pannaukseen.",
    "Hyvä kuva on aina kompromissi ja joskus se on hautajaisvieraat jotka joutuu joustamaan.",
    "Tue lautanen lautasliinalla hieman kallelleen ruokakuvia ottaessasi.",
    "Muista putsata digikameran kenno ennen kuin otat kuvia aukolla f/16.",
    "https://www.rajalacamera.fi/kaytetyt/ennakkomyynti",
    "Lyö vaan lujaa sen filmipurkin pöytään nappulapuoli alaspäin niin aukee helposti.",
    "Hento hiuslakkakerros UV-suotimen sisäpinnalla takaa kuviin taiteellisen herkän tunnelman.",
    "Jos haluaa laskea miltä etäisyydeltä saa aurinkomaisen valon, niin kertoo valonlähteen halkaisijan luvulla 107,5.",
    "Foma tekee ihmisestä valokuvaajana paremman.",
    "Valokuvaus on taidetta, tiedettä ja tekniikkaa sekaisin.",
    "Vesisateella kuvia voi ottaa vaikka parkkihallissa",
    "Kehitteen toimivuutta epäillessä kannattaa suosiolla heittää se menemään. Harmittaa vähemmän kuin feilannut kehitys.",
    "Yhtäkään edittijäbää ei ole koskaan harmittanut B-rollin paljous."
    '"I have too much footage" -No filmmaker ever',
    "Jätä potrettipisteellä kuviin tarpeeksi tilaa kropata",
    "Hammastahna toimii takanäytön naarmujen fiksaamiseen",
    "Kuvaa filmiä herkällä liipasinsormella. Jos näkyy kiva maisema niin kuva otetaan, siltä varalta ettei seuraava maisema ookkaan parempi. Jos on nyppylän huipulla niin sinne tuskin palaa hetkeen, joten sieltä otetaan kaikki kuvat mitkä kiinnostaa ja sit mennään pois.",
    "Älä tee elämässä virheit",
    "Kamerat ovatkin hyvä esimerkki siitä, miten pienenpienet erot luodaan algoritmeilla. OnePlussan kameran toistamat värit ovat valjuimpia, mutta samalla realistisimpia. Silmää miellyttävin kuva ei ole aina se paras.",
    "Keikan alkuu synkkakuvat kengistä aina",
    "Juhlat palvelevat kuvaajaa\n\nEiku mites tää ny meni",
    "WARNING:\nAIRPORT X-RAYS CAN RUIN YOUR VALUABLE PHOTOS!",
    "Muista puhdistaa kenno ennen f/16 kuvauksia",
    "Kantsii kyl satsaa nyt henkiseen hyvinvointiin ja ihmissuhteisiin ja jättää rahan miettiminen vähemmälle",
    "Protip jalustakuvaamiseen lumihangessa: laita jalat vähän suppuun ja tökkää sitten lumeen niin jalat leviävät upotessaan syvemmälle. Jos jalat ovat valmiiksi lukkoja vasten, jalusta jää kellumaan hankeen eikä asetu kunnolla.",
    "Jos kuvassa mikään kohta ei pala puhki nii laita salamaan lisää tehoa",
    "Taidetta ei tarvitse ymmärtää, eikä kaikesta ei tarvitse tykätä. Kaikki kysymykset ja kokemukset ovat sallittuja!",
    "Sumu on ihmisen parasta aikaa",
    "Hyvät yöunet on tärkeempää ku aikainen toimitus",
    "Rungon kohinansiedolla ei oo väliä jos herkkyyttä ei tarvii nostaa",
    "Kuva on turha jos sen vaikuttavuus on pikseleitä kiinni",
    "Muistikortit nimetään vikisemättä",
    "Jos tekee mieli olla sisällä, ulkona saisi hyviä kuvia.",
    "Jos kuvasi jäävät pimeäksi käyttäen Sunny16-sääntöä, hanki tehokkaampi salama",
    "Full power. Aina.",
    "Muovispiraalit ei kestä kiehuvaa vettä",
    "Foma on uusi musta",
    '"Taide on ihan perseestä."\n -Laura Nissinen',
    "RTFM",
    "Tässä ryhmässä pitää olla aina vähän varovainen",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
    "Kantsii hakee hallitukseen...",
]

stickers = [
    "CAACAgIAAxkBAAEGLcFjVXtSE9izknqchIxJRUklPL0koQACHgEAAiHfMQE_pcz3yBGAdyoE",
    "CAACAgIAAxkBAAEGLcNjVXtTDDnZHG7TlXp1SKnH1rEbFAACHwEAAiHfMQEXT1Wc5kaV8ioE",
    "CAACAgIAAxkBAAEGLcVjVXtVMmD2Izn3KYGXRPcTHAwUggACIAEAAiHfMQHFbatSWwQ6myoE",
    "CAACAgIAAxkBAAEGLcljVXtbzSG0jhapfW7zKJv0SfVxOgACIQEAAiHfMQEwSd7-kQ3ZzyoE",
    "CAACAgIAAxkBAAEGLctjVXtc0noo-9ASvT7l4gABuv4h0owAAiIBAAIh3zEB1lHZ_FtEliIqBA",
    "CAACAgIAAxkBAAEGLc1jVXtfj6MNQbEQltlGzTm-lnWeQAACIwEAAiHfMQHomsn1D7HKgyoE",
    "CAACAgIAAxkBAAEGLc9jVXthsIOv9h8yUHij-GYs0U1p6wACJAEAAiHfMQE_3L8FUCy5mCoE",
    "CAACAgIAAxkBAAEGLdFjVXtjBxlVyfE6Iu3Wkd36l2RN7gACJQEAAiHfMQHoa0eq8gMQQioE",
    "CAACAgIAAxkBAAEGLdNjVXtku-WB0M2y1o3lBVmM4clBMQACJgEAAiHfMQFfuet8AQonfSoE",
    "CAACAgIAAxkBAAEGLdVjVXtno0EdxcvUDYHibY27PwJ1ogACJwEAAiHfMQFbUFb_ZvhP3yoE",
    "CAACAgIAAxkBAAEGLdxjVXufZK4-VTrdMUf4jYcFHMEX8AACKQEAAiHfMQEzSzvBQXK6ZCoE",
    "CAACAgIAAxkBAAEGLd5jVXvDYI6hzAwY1BKXM3CptxlZsAACKgEAAiHfMQHFRCZkdTPsPioE",
    "CAACAgIAAxkBAAEGLd9jVXvD_BjE__ecArTsEAJMkrfoUQACKwEAAiHfMQFErv4OBIMsmioE",
    "CAACAgIAAxkBAAEGLeFjVXvE9tlZ9M0AAcPi8w8P4vvd1oUAAiwBAAIh3zEBR9JHB0x-JC8qBA",
    "CAACAgIAAxkBAAEGLeNjVXvFueNbB9SLaMxgFi_Gkh-ouwACLQEAAiHfMQEjqKVrImVu-SoE",
    "CAACAgIAAxkBAAEGLeZjVXvHeW1GbOYHhDeLMXEPuAHZPAACLwEAAiHfMQFW2k6yC7S89ioE",
    "CAACAgIAAxkBAAEGLedjVXvIj8TIvnyP2CCoJST4EJv1ogACMAEAAiHfMQHOeD8t4RpKdSoE",
    "CAACAgIAAxkBAAEGLeljVXvI_2UDPJu7V9XkBoZGqE-MggACMQEAAiHfMQEV_vOfugxzWSoE",
    "CAACAgIAAxkBAAEGLetjVXvJSWEFpNQtVcCqS9NsT_pHuwACMgEAAiHfMQGvwJ0R7hkY1yoE",
    "CAACAgIAAxkBAAEGLexjVXvKWdhpsXFE2ASYtwWwjuvmNgACMwEAAiHfMQGo7x3k4zYV2CoE",
    "CAACAgIAAxkBAAEGLe9jVXvLzPM1azgaIfBcSjK3RL63VQACNQEAAiHfMQEXYrv_e-bTTSoE",
    "CAACAgIAAxkBAAEGLfFjVXvMWTgyofnaWJFJz8JEA3NTfwACNgEAAiHfMQG61gVJBdYGsioE",
    "CAACAgIAAxkBAAEGLfNjVXvMV3ISBbckl3NYc6tY2CUXlQACNwEAAiHfMQFCOmLZRIWT6yoE",
    "CAACAgIAAxkBAAEGLfRjVXvN-Rum4zVlwlliuCx1FAswBQACOAEAAiHfMQHrVlMzh_6spCoE",
    "CAACAgIAAxkBAAEGLfZjVXvOSsgIDEi9jhZpGyfKZWoa5gACOQEAAiHfMQERN2AYOZOWSCoE",
    "CAACAgIAAxkBAAEGLfhjVXvOkWrrWpsfvbTdu0p2ExjKHgACOgEAAiHfMQGu8kHMV8j2ySoE",
    "CAACAgIAAxkBAAEGLfpjVXvPCVXe5aHXCfUd0lGwSEC9lgACOwEAAiHfMQEGEuo2aOVjJSoE",
    "CAACAgIAAxkBAAEGLftjVXvQg8q64YlCM29M5Ub9Ev5VfAACPAEAAiHfMQFoe7pULYz-dioE",
    "CAACAgIAAxkBAAEGLf1jVXvQ8jagpxphnZEKsJ7jHySS1gACPQEAAiHfMQHQWA2hUjh8vCoE",
    "CAACAgIAAxkBAAEGLf9jVXvROXakvWVA2auLeXBTqRkB2AACPgEAAiHfMQEBK8_HYkAw-CoE",
    "CAACAgIAAxkBAAEGLgFjVXvSBA2bAuad8XEoPB5o-ScCoQACPwEAAiHfMQHrlpGey2GaBCoE",
    "CAACAgIAAxkBAAEGLgNjVXvTgQI6JhohVI2obJkgXOEGKgACQQEAAiHfMQFYXPeFrSBPuyoE",
    "CAACAgIAAxkBAAEGLgVjVXvTvkR4Qi_RD-pHDvLZR63XLwACQgEAAiHfMQHKWKsCqxM5cioE",
    "CAACAgIAAxkBAAEGLgZjVXvU1b8gyBhVe6z-UsMCKF_RgQACQwEAAiHfMQGCCNQVY5CTLyoE",
    "CAACAgIAAxkBAAEGLghjVXvURtua7nYwWuVaVXNFD7RknwACRAEAAiHfMQEjK6BNOC5rCyoE",
    "CAACAgIAAxkBAAEGLgpjVXvV4lIqeHXMFRwWt4YSHGCUpQACRQEAAiHfMQHW9PRFzhQoZCoE",
    "CAACAgIAAxkBAAEGLgxjVXvW3iJbfbS3zDP9ucr7xF3oPQACRgEAAiHfMQEMAyG-sEgxrioE",
    "CAACAgIAAxkBAAEGLg1jVXvWnSAeVZJ9L7_NbaaHLIfPsQACRwEAAiHfMQHOxPVx9eNNICoE",
    "CAACAgIAAxkBAAEGLg9jVXvXo5eF36gQiJd5T9pF7s2UfQACSAEAAiHfMQGq1R_wa4ap2ioE",
    "CAACAgIAAxkBAAEGLhFjVXvXXYXYMjD8l5qT16L1FF027AACSQEAAiHfMQHR0uPDC-ssICoE",
    "CAACAgIAAxkBAAEGLhRjVXvZ1vYwMk7DlStJoCb-YDIQtgACSgEAAiHfMQGeuKccHIxTiSoE",
    "CAACAgIAAxkBAAEGLhVjVXvaRwv7YhKuNz_RhWxTWc2hgQACSwEAAiHfMQF0mzKYuZVXuioE",
    "CAACAgIAAxkBAAEGLhdjVXvaTVi-oGSZg2dZsGmei95y7wACTAEAAiHfMQFgXcLQwWfD1ioE",
    "CAACAgIAAxkBAAEGLhhjVXvb4EiBPqh3khgarS7MwSh4NgACTQEAAiHfMQGb4drs7-FhQioE",
    "CAACAgIAAxkBAAEGLhpjVXvbplIvBOJ06a97PeLdZmiUKQACTgEAAiHfMQHkWkplHFuxVCoE",
    "CAACAgIAAxkBAAEGLhxjVXvcxiqoP1zyR849seRogXaryAACUAEAAiHfMQEjg89jLqNZRyoE",
    "CAACAgIAAxkBAAEGLh5jVXvd7aMwKsUBZNyGfQufGIZEvgACUQEAAiHfMQGuVHW-0Kg5oioE",
    "CAACAgIAAxkBAAEGLiBjVXveJXV_YxcoLEVNLrnOEKdRrAACUgEAAiHfMQG_AwlZi-ab_CoE",
    "CAACAgIAAxkBAAEGLiFjVXveeyDba0dlHFaPrVUyLI-HXAACUwEAAiHfMQED0CHHsXGHtSoE",
    "CAACAgIAAxkBAAEGLiNjVXvfUpAcY-ZjLoYhIznscIFBAgACVAEAAiHfMQH9vGRFLm4d9CoE",
    "CAACAgIAAxkBAAEGLihjVXviLHd5DE6TyY98h4CfsIhOfAACVQEAAiHfMQFv5JKpEW4QGCoE",
    "CAACAgIAAxkBAAEGLiljVXvjsVoLqQeE5dVX0NS2FYfBMgACVgEAAiHfMQFsPVcOZrC2jyoE",
    "CAACAgIAAxkBAAEGLitjVXvjjnCHtmGHvQQizIKxR1561gACVwEAAiHfMQFuOEMNWqo-QyoE",
    "CAACAgIAAxkBAAEGLi1jVXvkYTWoiafGyqcMCxYyIxUi3wACWAEAAiHfMQGjq2hl9HI_CioE",
    "CAACAgIAAxkBAAEGLi9jVXvlfYfgMhLiTzVRjKobcifPwQACWQEAAiHfMQH71GuNwMpcsioE",
    "CAACAgIAAxkBAAEGLjJjVXvnsk0at2PEWmpC7uJFbh7ufwACWgEAAiHfMQGs2CuwQkAmgCoE",
    "CAACAgIAAxkBAAEGLjRjVXvoFlxNl-ldElIsiWLfjD2WbwACWwEAAiHfMQFh2CSKikvERCoE",
    "CAACAgIAAxkBAAEGLjZjVXvoAWAN_C_OWt1bhulrLo8_3gACXAEAAiHfMQE5KvPZW35kRyoE",
    "CAACAgIAAxkBAAEGLjhjVXvpTZIRVGyrIxWyjPNweSZtfQACYgEAAiHfMQHEZkK39rvOdyoE",
    "CAACAgIAAxkBAAEGLjpjVXvqpfl-XWXG24DbBaNdx037bAACYwEAAiHfMQGjv2Vw8OqCJyoE",
    "CAACAgIAAxkBAAEGLjxjVXvrc_bDpAJrs7ZB0gVKSQPebwACZAEAAiHfMQFl6hmLds_8TyoE",
    "CAACAgIAAxkBAAEGLj5jVXvr__h1EkGiToFF-OCLRdNnJAACZQEAAiHfMQEF-s-5Z9fLxCoE",
    "CAACAgIAAxkBAAEGLj9jVXvsrPIaul4d3Dm-2MpdjBEL3wACZgEAAiHfMQHXwmgcCRSEcSoE",
    "CAACAgIAAxkBAAEGLkFjVXvtoB9wlQ7hxDNfrY2WGVx9rAACZwEAAiHfMQEajH_fajGpgCoE",
    "CAACAgIAAxkBAAEGLkNjVXvulZ1pwj2AWaXrHO4kBuu0vgACagEAAiHfMQHXMc1kdoyoSCoE",
    "CAACAgIAAxkBAAEGLkVjVXvuWffLcWDYVsaP6A5_LZ7R4QACbgEAAiHfMQHPc3takXyvFCoE",
    "CAACAgIAAxkBAAEGLkdjVXvvUPNkirPhHoMF_mMy3LGz0gACcAEAAiHfMQHQJx7p7Wt1AyoE",
    "CAACAgIAAxkBAAEGLkljVXvwct6x2mEI_c-19KR9SxxSXAACcQEAAiHfMQG2Y2I9CLLTiCoE",
    "CAACAgIAAxkBAAEGLktjVXvx1Q0z7eE5rTuH52KYSGeC3QACcgEAAiHfMQESctYMM215wyoE",
    "CAACAgIAAxkBAAEGLk1jVXvynfHLuMDawISFaLb1QXtNrwACdAEAAiHfMQGre_k4TlI22ioE",
    "CAACAgIAAxkBAAEGLk9jVXvzQh1WYBQC_dUjvUu2CRWxjgACdQEAAiHfMQGao0GftT-9ySoE",
    "CAACAgIAAxkBAAEGLlFjVXv0LR-mjfrjFkkOMFydPKkAAQIAAnYBAAIh3zEBapD6X9YGVxwqBA",
    "CAACAgIAAxkBAAEGLlNjVXv0oVQ7ErshRZ0CqJVSgvqNhwACdwEAAiHfMQFcpcpuSrzuLCoE",
    "CAACAgIAAxkBAAEGLlVjVXv1MRc2qYwwv5v8YlcGw9Le0gACeAEAAiHfMQH77vT60mBnbyoE",
    "CAACAgIAAxkBAAEGLldjVXv2oIwSr45fFHSrvAUp1coE0QACeQEAAiHfMQG5lkwOt8KoXyoE",
    "CAACAgIAAxkBAAEGLlljVXv3XY7zDF6q45UlxgTwam3LywACegEAAiHfMQFuHqE--0SLJyoE",
    "CAACAgIAAxkBAAEGLlpjVXv39OALPzvsDAkWb1bR36xq2gACewEAAiHfMQG0bC4JrU3-TyoE",
    "CAACAgIAAxkBAAEGLlxjVXv42xC_a7u1Wc01xsOKagsB8wACfAEAAiHfMQGhyBq3V8e5_yoE",
    "CAACAgIAAxkBAAEGLl5jVXv5ziJcl4Cy60nxdHCvGVN2ZQACfQEAAiHfMQEDVlSkIzqUdSoE",
    "CAACAgIAAxkBAAEGLmBjVXv5u6mFuEqhzeYQqIyN63jQfQACfgEAAiHfMQH_J3Bj2hEEoCoE",
    "CAACAgIAAxkBAAEGLmNjVXv7wbNOkCwPJPdoFvi7dwABjkIAAn8BAAIh3zEBoANEDVAD8AABKgQ",
    "CAACAgIAAxkBAAEGLmVjVXv8WVDMt_bpGQ4ivmXwO5xzuAACgAEAAiHfMQGTLJts_WwIqioE",
    "CAACAgIAAxkBAAEGLmhjVXv-ozW8Q31pUdlCS0ZXhD0Y7wACgQEAAiHfMQEpRfiCoGU4_SoE",
    "CAACAgIAAxkBAAEGLmpjVXv_3DriHJuVUOZuX1biptu4kQACggEAAiHfMQGZeXtPEZl6lCoE",
    "CAACAgIAAxkBAAEGLmxjVXv_iDk2OC3GxPawGsB59VqmCgACgwEAAiHfMQHVtJLzOS3qcyoE",
    "CAACAgIAAxkBAAEGLm5jVXwAATivkNAFQDjRqLJP2LeRZNgAAoQBAAIh3zEBxAb6OtJRMUMqBA",
    "CAACAgIAAxkBAAEGLnBjVXwB-kqNHUd6oLmK6l0oZdewxAAChQEAAiHfMQHVzelW-y_gJSoE",
    "CAACAgIAAxkBAAEGLnFjVXwCOXUk0OWMKc7r927xLeizmAAChgEAAiHfMQEePvo7C32xqCoE",
    "CAACAgIAAxkBAAEGLnNjVXwCjQ-1wg74IjxcAAFg0TtqoYsAAocBAAIh3zEBxe2OOh9tfO0qBA",
    "CAACAgIAAxkBAAEGLnZjVXwE2k0k9ja4HxK1XUHKjYJIawACiAEAAiHfMQGURu1S2eFwsioE",
    "CAACAgIAAxkBAAEGLntjVXwHpzfkajVVRWUQHAJBUK0vRgACiQEAAiHfMQFglFtDobrP0yoE",
    "CAACAgIAAxkBAAEGLn1jVXwI7K7HTYe4WvExBgQbNPQMTAACaAsAAsQnQUqIElsFcFE9sSoE",
    "CAACAgIAAxkBAAEGLn9jVXwJkw13Bbcx9obJ62JJTPddRQAC7A0AAvchgUi2IqHpIMGewyoE",
    "CAACAgIAAxkBAAEGLoFjVXwJeYZmYXEKWNuqpfxitHgncgACqw4AAtQ7SEk_2MA4wHzKbyoE",
    "CAACAgIAAxkBAAEGLoJjVXwKqlzs-tq_q7SJxpsgTdpZvwACMw4AA2BxSKc_s7_7Xs8cKgQ",
    "CAACAgIAAxkBAAEGLoRjVXwLtGtz2WhT1V-SM7Br013yWgACVhEAAv2iiEgkHzk_GQIDFCoE",
    "CAACAgIAAxkBAAEGLoZjVXwLeg334NfutaYLNyx8Sxo74QAChQwAAudbAAFJhVueX5a5fIEqBA",
    "CAACAgIAAxkBAAEGLohjVXwMgr3vS2mWWnxcPV8erDjaKwACqxMAAmkeSUkUd7iYNktecSoE",
    "CAACAgIAAxkBAAEGLoljVXwN7RAAAemVRikQ5JITuCJj32IAAtAOAAJkglBJ9kIoxteD9awqBA",
    "CAACAgIAAxkBAAEGLotjVXwNios7tKiYI__P6823HMtFRwACVxAAAiPPoEoTB3QQwjOiQyoE",
    "CAACAgIAAxkBAAEGLo1jVXwONmus3FpwBgdeiaVgzHP1YAACARUAAv5wqErWLa6X3pZzVSoE",
    "CAACAgIAAxkBAAEGLo5jVXwPjMFAHyjDFAjbfjA9f5cwTAAC0RIAAmA0-EoiLzh8SZ52iyoE",
    "CAACAgIAAxkBAAEGLpBjVXwP9gZGXm6Kf4X5iaDQs1W57QACDRAAAgTLQEtDdo_vIC6hJioE",
    "CAACAgIAAxkBAAEGLpJjVXwQi_NO9COMBvdYwPtXdAh9fwACTBEAAg5j0UuWzxwEDXbQhSoE",
    "CAACAgIAAxkBAAEGLpNjVXwQ4NK8iqBzJn2-vxWU3SMgoQACdRAAAoui0UvDGBz15QwFOSoE",
    "CAACAgIAAxkBAAEGLpdjVXwTKgxRtvDvfz-z0NSLtakkNAACVxEAAghyeEi3_MhOLgJmDSoE",
    "CAACAgIAAxkBAAEGLpljVXwTelxohFUHM3tjl_4FznrAmgACoRMAApGlsEhlScBVqdeSRCoE",
    "CAACAgIAAxkBAAEGLppjVXwUA8waQrm-B3p08rpKQaizbAACnhAAAviGUEnHSgTGhp503yoE",
    "CAACAgIAAxkBAAEGLpxjVXwUhuZ6ZA1sUL_WwDEGMoxs2QACaRQAApvGwEpyQmwMcwACWSoE",
    "CAACAgIAAxkBAAEGLp5jVXwVXzKLRjW_yeUH1pZI-772QQACTQ8AAtkAAcBKVyKC2u4WG2wqBA",
    "CAACAgIAAxkBAAEGLqBjVXwW_7rPz-PGiVmXpihyStml4AACMRcAArkqMEpdeJ9VOXMdDCoE",
    "CAACAgIAAxkBAAEGLqFjVXwWnAk2FSq6yt1KEgF3CM5CfQACYxYAApBVsUo_B704oQcdMioE",
    "CAACAgIAAxkBAAEGLqNjVXwXPI9ZpHGzrDsLHtPhut91GgACmhsAAlvukUuJQ-TudS4BdSoE",
    "CAACAgIAAxkBAAEGLqVjVXwYki0z79r0EibU6KULY7KXRQACzxgAAqbNyEsaeXBMWqLNAAEqBA",
    "CAACAgIAAxkBAAEGLqZjVXwY9eENuo_QqmIQ-VfKY4VnywACyxcAAiVm8EuuyE7f-GgisioE",
    "CAACAgIAAxkBAAEGLqhjVXwZIqkaAkyc31ktBx2utPNtJQACWBwAAtLAOEn5Z8d2riUctCoE",
    "CAACAgIAAxkBAAEGLqpjVXwZfTbHaFKUqqGPnW84YoeGNgACoBYAAspTmEmpR_xaVEMssioE",
    "CAACAgIAAxkBAAEGLqxjVXwafxBvcexj-QqepD3i7yeHpAAClxgAAvMtmUrXwRQhchkGCCoE",
    "CAACAgIAAxkBAAEGLq1jVXwbLphQQw4EEtiI-Aben7G76QACvh4AAkdZKUqdaZUNOBOhwyoE",
]
