tips = [
    "Laita kohde varjoon!",
    "Reeniä reeniä!",
    "Vaihda canoniin!",
    "Vaihda nikoniin!",
    "Vaihda sonyyn!",
    "Vaihda smenaan!",
    "Rembrandtit kuntoon!",
    "Hommaa savukone.",
    "Horisontti suoraan!",
    "Nosta tummaa alapäätä.",
    "Aina voi vetää mustavalkoseks.",
    "Osta kalliimpi kamera!",
    "vitsisauna.preset",
    "Puolipilvinen on paras kuvauskeli. Ei muutaku F22 ja iso400 sekä haarukointi -2/3. Ei voi epäonnistua ja jos epäonnistuu niin tiputa f22->f11.",
    "'No ei se väline siinä oo se oleellinen. Mul on ykköset sit muista syistä.'\n-Petri Mast 2018",
    "Kuvaisit filmiä.",
    "Jos ei oo mallia niin aina voi kuvata omia jalkoja.",
    "Yhtäkään raajaa ei leikata!",
    "Clarity aina 100.",
    "Kultainen leikkaus tai mene roskiin.",
    "1.4 ei himmennetä koskaan.",
    "1.4 voi joskus himmentää.",
    "Älä käytä sigmaa oikeissa kuvauksissa!",
    "Älä käytä f22, kun kuvaat makroja. Diffraktio on vittumainen suure.",
    "Parhaat kuvat sisältää aina vähän syntiä ;)",
    "Muistakaa käyttää P(rofessional)-modee!",
    "Kovalevytila on halpaa ja pilvipalvelut rajattomia <3",
    "Valovoima on ylivoimaa.",
    "Laskeudu koiran tasolle.",
    "Pidä kädessäsi lelua tai ruokaa ja heiluttele sitä linssin ympärillä.",
    "Kärsivällisyyttä.",
    "Älä osta presettejä!",
    "Sammuta kamera kun irroitat vakaajallista putkea.",
    "Jos filmillä epäonnistuu, niin voi kattoo vaan peiliin ja nähdä mistä se epäonnistuminen johtuu.",
    "Manuaalilla ku tarkentaa niin aina osuu.",
    "Kyllä sillä roskalavalta noukitulla keksipurkillakin saa kunnon kuvaa osaavissa käsissä.",
    "Joistakin malleista ei millään saa elävän tuntuisia kuvia. Tällöin yksi cocktail auttaa hyvän tuloksen saamiseksi paremmin kuin yhden voimakkaan lampun antama lisävalo.",
    "Mitä vaikeempi asento sen taiteellisempi kuva!",
    "Gammasäteily ei häikäise.",
    "Paras kamera ei ole kaikille sama.",
    "Osta sääkin oma Smenas, ne ei paljon maksa!",
    "Tarkista kaikkien kameroiden kellot ennen ku alat vetää.",
    "Kuivaa jalusta huolella jos uitat sen kokonaan järvessä.",
    "Treenaa pohkeita.",
    "Mene mukaan tilanteisiin hienovaraisesti.",
    "Smenalla: Aukko f/11 tai 16, tarkennus mieluummin ylä- kun alakanttiin.",
    "Isolla aukolla vain jos on pakko.",
    "Jos kuvasi tulee päätymään Aamulehteen (Moro) niin varmista, että kuvaat vaakakuvia.",
    "Servo päälle ja nappi pohjaan ja kotona sitten katotaan kuvat.",
    "Skannaa mieluusti negat muualla ko keittiössä, staattinen sähkö vetään puoleensa leivänmuruja.",
    "Smena on täydellinen.",
    "Kameroita ei voi olla ikinä liikaa.",
    "Passikuvan voi ottaa vaikka puhelimella kotona, siin ei oo kovat vaatimukset.",
    "Julkaiskaa enemmän, saa palautetta ja myöhemmin saa myötistellä eiku siis näkee kuinka on kehittyny kuvaajana.",
    "Yksi konsti spiraaliongelmissa on lyödä spiraali napakasti pari kertaa pöytään. Tärähdys saa filmin siellä loppupäässä \"rentoutumaan\" ja taas kulkemaan.",
    "Älä myy vanhaa kuvauskalustoa liian äkkinäisesti pois, se saattaa kaduttaa jälkeenpäin. Filmikaman arvo tuskin laskee vaikka miettisit pari vuotta.",
    "'Buzz, this is Houston. F/2 - 1/160th second for shadow photography on the sequence camera.'\n-Apollo 11 Mission Control, 109:23:26",
    "Kaamoksen taittaa iso kuvakoko, mustavalkofilmi ja vedenpitävät jalkineet.",
    "Käytä aasialaista kuvausohjetta: ota kuvia kaikkialla, kaikesta ja kaikista mahdollisista asennoista.",
    "Vain peilin kolahduksesta läsnäoleva yleisö tietää, että paikalla on myös oikea ammatti_kuvaaja.",
    "Hyvän tarjouksen tullessa vastaan kannattaa ostaa heti. Jos et osta heti, joku muu sen kyllä ostaa pois. Ja nettikaupasta ostettaessa kannattaa muistaa palautusoikeus tavaroille.",
    "Kääri moottoripyörän kahvanlämmitinmattoa kameran rungon ja putken ympärille jos näpit jäätyy talvella",
    "Eihän sitä harrastajakuvaaja muita kun testikuvia kuvaakaan",
    "Myyntihetki ajoitetaan perikunnan toimesta",
    "Sijoita kerralla parempaan runkoon, jonka kanssa pärjäät useamman vuoden.",
    "Älä osta f/1.8 objektiiveja koska pian tarvitset kuitenkin f/1.4.",
    "Älä aseta kolmijalkaa minkään automaattisesti liikkuvan taakse",
    "Huonolla ilmalla tulee parhaat kuvat",
    "Kun olet käyttänyt 10k€ kalustoon, on aika opetella kuvaamaan",
    "Neliössä kaikki on aina vähän keskemmällä.",
    "Pöh! Valokuvaus on jalo taiteenlaji, joka palkitsee tekijänsä. Sen parissa köyhäkin sielu kultivoituu. \n - Aku Ankka",
    "Aloittelijan ei kannata hamstrata kaikkia lisävarusteita kerralla, mutta taitojen karttuessa tarpeellisia osia voivat olla ainakin muistikortti",
    "ISO 12800:aa pienempi on vaan terävyyttä",
    "Autot kuvataan \"aina\" sellaselt korkeudelt et näkyy ali :) \n - Mestari",
    "Tee presettejä!",
    "Kuvassa on luonnetta kun se on vähän ohi tarkennettu.",
    "Jos kuvasi tulee päätymään Vapriikin kuva-arkistoon, niin varmista, että kuvaat 6x6-kuvia.",
    "Ammu vain HP5+. Ei tarvi miettiä.",
    "Laita aina kolmijalan yksi jalka linssin suuntaan. Jos jalusta kaatuu, niin se ei ainakaan rysähdä suoraan etuelementti edellä asfalttiin.",
    "Pieni tähtäysreikä keskelle reflaa, niin on helppo suunnata oikein.",
    "Muistakaa printata hyvät kuvanne!",
    "Muiden filmiperiä ei avata ilman lupaa!",
    "Lämmitä kehite suljetussa astiassa. Vituttaa kun keitinlasi kaatuu vesihauteeseen.",
    "Sunny16 on se, kun aurinko paistaa niin, että silmiin sattuu. Sit, jos ei satu, stoppi vähemmän.",
    "Ei ikinä Sastamalaan ilman kamerakalustoa",
    "Skumppapullo on muuten paljon helpompi pitää kuvatessa kädessä kuin tuoppi.",
    "Kannattaa retkuu ennen naimisia.",
    "Luonto ei toista itseään. Jos näet hyvän aiheen hyvällä valolla, ja ajattelet että kuvaan tuon huomenna, ei onnistu. Huomenna se on aivan erilainen, ja jää kuva saamatta.",
    "Silmillä voi tallentaa ja nauttia ympäristöstä ilman, että kamera on koko ajan kädessä.",
    "Kuvaisit digiä!",
    "Ammattilainen ei napsi eikä räpsi. Hän hakee kuvat.",
    "Kissanpentuja kuvatessa väsytä ne leikkimällä ensiksi. Sen jälkeen ne jopa saattaa pysyä paikoillaan sen hetken.",
    "Muista suojaviiva",
    "Tarkista valkotasapaino ennen kun kuvaat",
    "Fix it in post",
    "Suljinaika = 1/(2*framerate)",
    "Muista purku",
    "Varmista että kuvakoko vaihtuu tai kuvakulma muuttuu riittävästi, jos leikkaat saman kohteen kuvien välillä",
    "Staattinen kuva on joskus parempi kuin tärisevä ajo",
    "Skarppaa!",
    "Käynnistä REC vasta kun klaffi on kuvassa. Tällöin se näkyy videon previkassa suoraan.",
    "\"Slow is smooth and smooth is king\" -Stefan Czech",
    "Akkujen ja muistikorttien kanssa +1 -periaate, mukaan yksi enemmän kuin luulet tarvitsevasi",
    "\"I have too much footage\" -No filmmaker ever",
    "Oikee meininki on alkaa näpyttelee numeroo ja jos ei keksi mitään perustetta sinä aikana perua, painaa soittonappia.",
    "Ei tommosia jäädä miettiin vaan ostetaan pois ja kattellaan sit et mitä tuli tehtyä.",
    "Valokuvaus on vaa yks iso f-luvun maksimointitehtävä.",
    "Jokaisessa digipokkarissa taitaa olla jonkinlainen zoom. Jos ei ole niin jätä kamera kauppaan.",
    "Ledikeppiä voi himmentää sukkahousuilla.",
    "Lightroomin print-osasto on ihan näppärä jos haluu esim järkkärikuvistaan pdf:ää. Tosta vaan valitsee kuvat jotka haluu samaan tiedostoon ja painaa print.",
    "Osta mahdollisimman kallis kamera käytä siinä vain automaatti toimintaa.",
    "Kinohommissa kyllä todennu että se fiilis kuvatessa on kaikista tärkein. Jälki ei oo kuitenkaan hyvää niin siinä ei kannata sen kummemmin hifistellä.",
    "Kunhan kameralla on kiva kuvata niin se on kivaa",
    "Kameratorilla siihen tuotteeseen laitetaan arvoa testaamalla ja parhaassa tapauksessa huoltamalla se, Rahalassa arvo tulee siitä että se on Rahala.",
    "Amatöörit harrastkoot valokuvausta rauhassa kaduilla ja kerhoissaan.",
    "Kivempi lukee tiliotetta, ku ostokset aina luottokorttilaskulla.",
    "Ite otan yleensä lasin käteen niin, että vasen peukalo ja oikea keskisormi, joka painaa vapautuspainiketta, kohtaa, lasi menee paikoilleen. Voi vaihtaa pimeessäkin. Yleensä noissa on jotain tunnettavaa, joilla ton kohdan tunnistaa kokeilemalla. Korttipesän valo on pimeen puuhailuihin omasta mielestä parasta.",
    "Syväterävyysalue on verrannollinen etäisyyden neliöön, ja kääntäen verrannollinen polttovälin neliöön.",
    "Tarkennus on on aina kuvaajan tietoinen valinta.",
    "Treenaa forkkuja.",
    "Joku kans selitti että joillain af-rungoilla voi tarkentaa eka jolleki etäisyydelle (esim. vähä tolpan taa), laittaa focus priority:n shutterille ja painaa laukasunapin pohjaan -> kamera ottaa kuvan vasta ku kohde fokuksessa kameran mielestä.",
    "Odota että ryhmä ehtii kuvaan ennen ku kutsut seuraavan.",
    "Jos f/4 ahdistaa niin f/2.8 on kyllä turha päivitys.",
    "Retkahduksen hyvyyttä arvioidessa lienee selvää, että objektiivista hyvyysarvoa ei ole mahdollista määrittää millään sellaisella tavalla, että saatu hyvyysarvo olisi käyttäjän kannalta mielekäs mittari. Omalla kohdalla potentiaalista retkahdusta voi arvioida mitattavilla ja tosielämää vastaavilla suureilla, mutta tapahtunutta ja julkista retkahdusta ei tällaisilla ole järkeä arvioida. Lisäks pitää muistaa retkahduksen ja järkihankinnan ero: retkahdukseen kuuluu aina pieni \"no miksi ei\"-ilmiö, järkihankinta vaan tehdään kun se on järkevää.\n\nFilmiformaateissa on vähän sama tilanne. Formaatin paremmuutta toiseen nähden voi perustella mitattavilla suureilla, kuten saavutetulla kuvan tarkkuudella, mutta valinnan jälkeen käytössä oleva formaatti ei enää kovin oleellinen ole kuvaamisen kannalta. Lisäksi formaatti vaikuttaa moneen muuhunkin kuvaamisen kannalta merkittävään asiaan kuin itse lopputuotteeseen, jolloin yleisen hyvyysarvon määrittämisestä tulee turhan työlästä.",
    "Jos yrityksesi lähetys pitää tullata, jätä tulli-ilmoituksen tekeminen suosiolla rahtiyritykselle.",
    "Tarkenna aina lähimpään silmään.",
    "Kun alat tehdä kokeiluja valaistuksella, kokeile ensin pehmoleluilla. Ne ovat malleja kärsivällisempiä, ja alussa tarvitset kaiken mahdollisen kärsivällisyyden.",
    "Väkevän auringonlaskun tunnistaa siitä, että se näyttää hyvältä mustavalkoisena.",
    "Käytä Fairya tai muuta nestemäistä astianpesuainetta filmin loppuhuuhtelun yhteydessä. Saat valumajäljettömän filmin ja kehitetankin pestyä samalla kertaa.",
    "Vain kalleimmat kamat on parhaat.",
    "Experiences don't have to be positive as long as they are strong.",
    "Älä koskaan käytä vesileimoja jos haluat arvostusta kuvaajana :)",
    "Älä säilytä oluttölkkiä kameralaukussa.",
    "Jatka videon tallennusta aina muutama sekunti pidempään kuin pidät tarpeellisena.",
    "Jos aiot zoomata tallennuksen aikana, älä aloita zoomausta heti tallennuksen käynnistyttyä. Kuvaa ensin muutama sekunti kohdetta, käynnistä zoomaus ja pidä tallennus päällä joitakin sekunteja zoomauksen päätyttyä.",
    "Uljaat prinssit kuvataan alaviistosta.",
    "Jos löydät houkuttelevan tarjouksen, sovi kaupat välittömästi ja mieti logistiikkaa vasta sen jälkeen.",
    "Oikeisiin kuvauksiin sit Canonit.",
    "Ninja walk roskiin",
    "Kun kuvaat lumista maisemaa niin muista kompensoida valotusta vähintään yhdellä stopilla.",
    "Jos lähdet kuvaamaan ja filmissä on jäljellä vähemmän kuin viisi ruutua, vaihda filmi.",
    "Aina mukaan vähintää kolme kameraa eri setupeil et saa lauottuu joka sormel eritahtiin ja yks jäähtyy ettei suljin polta filmii.",
    "Take your time become a better photographer and learn more about editing software",
    "Voit ajatella ton ostamisen sijoituksena inspiraatioon",
    "There are no presets \"one size fits all\" I had downloaded 500 of these 99% are worthless.",
    "älä osta halpoja sdi kaapeleita, edes patch kaapeleiksi",
    "Pidä akut pakkasella sisätaskussa.",
    "Aika antaa arkiselle kuvalle arvon.",
    "Luottotiedot kannattaa säilyttää.",
    "Torikuvan urlista kun vaihtaa loppuun original, niin saa hieman isomman kuvan: https://images.tori.fi/api/v1/imagestori/images/6171628697.jpg?rule=original",
    "Parhaat kuvat otetaan huonolla kelillä.",
    "En tiedä mitä täällä on keskusteltu, ku en jaksa lukee, mut tärkeintä on se, että\n-kamera sopii omaan käteen\n-rungon hinta ja tulevien lasien hinta sopii omalle lompakolle\n-akkukesto jos jostain syystä kuvaat jotain infernaalisen pitkii settejä\n-kameran käyttöliittymä ei saa sua hermostumaan\n-antaa kaiken muun paskan speksivertailun olla",
    "Kaiken taiteen tehtävä ei ole miellyttää.",
    "Visualisoi kuva mielessäsi ennen laukaisua.",
    "Varastoon aina kuva taivaasta.",
    "Kato huomisen kamera jo tänään, ni voi käyttää huomisen palkat jo tänään.",
    "Jos haluaa oikeasti \"taidettaan\" esille ja tuoda ihmisille iloa (Tai järkytystä paskalla kuvalla, vaikka koiranpaskasta.. Taiteessahan on kyse tunteen siirrosta, kultaisenleikkauksen nuolennassa besserwisseröinnistä.. Yhtään kultaistaleikkausta väheksymättä..), niin kannattanee koittaa teoksiaan esille hieman vähemmän kuratoituihin paikkoihin.. Antaapa kaikkien kukkien kukkia.. Picassokin oli varmasti alussa paska maalari.. ",
    "Jos mietit kahen vaihtoehdon välillä ni osta suorilta molemmat, testaa kummasta pidät ja myy se toinen.",
    "LEICA is for masters, the immortals whose work lives forever, and for them, this newest APO-SUMMICRON-M 35mm f/2 APO is the only 35mm lens that will suffice.\n\nYou know who you are. Don't ask if LEICA is worth it; ask are you and your work worthy of LEICA? The quality is remembered long after the price is forgotten.",
    "Zoomaus on hyvä piilottaa pannaukseen.",
    "low brain people should stay away from difficult films",
    "Hifistelee sit medikkahommissa ja ostaa kolme Bronicaa.",
    "Tekee Toriostokset käteisellä niin se on kun rahaa ei menis ollenkaan",
    "Kameran käyttöohje.\n\nUlko kuvauskset:\nAurinkoinen pilvetön ilma.\n  Valotusnopeus 100. Aukko: 11\n  Kaukaa kuvattaessa\n  Aukko 8. Läheltä kuvattaessa.\n\nPilvinen ilma:\n  Valotusnopeus 50. Aukko 5.5\n  Läheltä kuvattaessa.\n  Aukko 8. Kaukaa kuvattaessa.\n\nSalamalaitteella kuvattaessa.\nValotus nopeus 50.",
    "Hyvä kuva on aina kompromissi ja joskus se on hautajaisvieraat jotka joutuu joustamaan.",
    "Canonit ei ookaan mitään kohinaisia pikkukennosuhruja.",
    "Aloita Lubitelilla, Kievin kanssa saattaa tulla ongelmia, eikä niihin kannata törmätä ensimmäiseksi.",
    "Tue lautanen lautasliinalla hieman kallelleen ruokakuvia ottaessasi.",
    "There is no image format quite so lovely as an 8x10 transparency.",
    "Muista putsata digikameran kenno ennen kuin otat kuvia aukolla f/16.",
    "Älä sommittele omaa varjoasi kuvaan, ellei se paranna kuvaa.",
    "https://www.rajalacamera.fi/kaytetyt/ennakkomyynti",
    "Zoomimiehen etiketti:\n- Ole hiljaa jos ei kysytä\n- Nosta kädet ilmaan ja laita kamera kaappiin jos et osaa kuvata primeilla\n- Hanki kissa",
    "Kytke night light pois editoidessasi kuviasi.",
    "Lyö vaan lujaa sen filmipurkin pöytään nappulapuoli alaspäin niin aukee helposti.",
    "Since film is more expensive than developer the following mantra is useful: When in doubt throw it out.",
    "Hento hiuslakkakerros UV-suotimen sisäpinnalla takaa kuviin taiteellisen herkän tunnelman.",
    "Jos haluu laskee miltä etäisyydeltä saa aurinkomaisen valon niin kertoo lähteen halkaisijan luvulla 107,5.",
    "Foma tekee ihmisestä valokuvaajana paremman.",
    "Sinänsähän se ei haittaa et lasi on terävä. Siihen nokalle voi sit laittaa kaikenlaisia suttufilsuja, ja sit saa pehmeetä kuvaa. Tai laittaa terävöitys 0 kuten mä tein sunnuntain kuville.",
    "Käytä tieteen menetelmiä kuvataiteen tekemiseen. Valokuvaus on taidetta, tiedettä ja tekniikkaa sekaisin."
]

stickers = [
    "CAADAgADHgEAAiHfMQE_pcz3yBGAdwI",
    "CAADAgADHwEAAiHfMQEXT1Wc5kaV8gI",
    "CAADAgADIAEAAiHfMQHFbatSWwQ6mwI",
    "CAADAgADIQEAAiHfMQEwSd7-kQ3ZzwI",
    "CAADAgADIgEAAiHfMQHWUdn8W0SWIgI",
    "CAADAgADIwEAAiHfMQHomsn1D7HKgwI",
    "CAADAgADJAEAAiHfMQE_3L8FUCy5mAI",
    "CAADAgADJQEAAiHfMQHoa0eq8gMQQgI",
    "CAADAgADJgEAAiHfMQFfuet8AQonfQI",
    "CAADAgADJwEAAiHfMQFbUFb_ZvhP3wI",
    "CAADAgADKQEAAiHfMQEzSzvBQXK6ZAI",
    "CAADAgADKgEAAiHfMQHFRCZkdTPsPgI",
    "CAADAgADKwEAAiHfMQFErv4OBIMsmgI",
    "CAADAgADLAEAAiHfMQFH0kcHTH4kLwI",
    "CAADAgADLQEAAiHfMQEjqKVrImVu-QI",
    "CAADAgADLwEAAiHfMQFW2k6yC7S89gI",
    "CAADAgADMAEAAiHfMQHOeD8t4RpKdQI",
    "CAADAgADMQEAAiHfMQEV_vOfugxzWQI",
    "CAADAgADMgEAAiHfMQGvwJ0R7hkY1wI",
    "CAADAgADMwEAAiHfMQGo7x3k4zYV2AI",
    "CAADAgADNQEAAiHfMQEXYrv_e-bTTQI",
    "CAADAgADNgEAAiHfMQG61gVJBdYGsgI",
    "CAADAgADNwEAAiHfMQFCOmLZRIWT6wI",
    "CAADAgADOAEAAiHfMQHrVlMzh_6spAI",
    "CAADAgADOQEAAiHfMQERN2AYOZOWSAI",
    "CAADAgADOgEAAiHfMQGu8kHMV8j2yQI",
    "CAADAgADOwEAAiHfMQEGEuo2aOVjJQI",
    "CAADAgADPAEAAiHfMQFoe7pULYz-dgI",
    "CAADAgADPQEAAiHfMQHQWA2hUjh8vAI",
    "CAADAgADPgEAAiHfMQEBK8_HYkAw-AI",
    "CAADAgADPwEAAiHfMQHrlpGey2GaBAI",
    "CAADAgADQQEAAiHfMQFYXPeFrSBPuwI"
]
